name: 'CI'

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        lisp:
          - sbcl-bin
          
    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v4
      - uses: 40ants/setup-lisp@v4
        with:
          asdf-system: greeting
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: greeting
          # see. https://github.com/40ants/run-tests?tab=readme-ov-file#custom-test-runner
          run-tests: |
            (ql:quickload "greeting/tests")
            (unless (symbol-call :greeting/tests :run-test) (error "Tests failed"))
